/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author Admin
 */
public class PenampilGambarCombobox extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarCombobox
     */
    public PenampilGambarCombobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pilihan = new javax.swing.JComboBox<>();
        pCardLayout = new javax.swing.JPanel();
        JavaScript = new javax.swing.JLabel();
        PHP = new javax.swing.JLabel();
        Python = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Pilih Gambaar");
        jPanel1.add(jLabel2);

        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JavaScript", "PHP", "Python" }));
        pilihan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihanItemStateChanged(evt);
            }
        });
        jPanel1.add(pilihan);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pCardLayout.setLayout(new java.awt.CardLayout());

        JavaScript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaScript.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\programming\\javascript.jpg")); // NOI18N
        JavaScript.setText("jLabel1");
        pCardLayout.add(JavaScript, "0");

        PHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PHP.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\programming\\PHP.jpg")); // NOI18N
        PHP.setText("jLabel3");
        pCardLayout.add(PHP, "1");

        Python.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Python.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\programming\\pythonL.jpg")); // NOI18N
        Python.setText("jLabel4");
        pCardLayout.add(Python, "2");

        getContentPane().add(pCardLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihanItemStateChanged
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(pCardLayout.getLayout());
        cl.show(pCardLayout, String.valueOf(pilihan.getSelectedIndex()));
    }//GEN-LAST:event_pilihanItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambarCombobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JavaScript;
    private javax.swing.JLabel PHP;
    private javax.swing.JLabel Python;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pCardLayout;
    private javax.swing.JComboBox<String> pilihan;
    // End of variables declaration//GEN-END:variables
}
